### ISSUE TITLE
error when trying to use hil_fetch()

### ISSUE THREAD

**Issue by raisin-toast** [asiripanich/hildar#6]
I keep getting an error on hil_fetch as it is failing the asserts in the function. I think this is caused by the fact that the naming convention may have changed and so the available files vector is empty. My current naming convention looks like `"Combined_[a-z]\\d{3}c.fst", rather than `"Combined_[a-z]\\d{3}u.fst"` which is what is contained in the function. I'd suggest making it agnostic to whatever letter the files end in. 

Happy to submit a pr if it would help. 

P.S. this looks like a great package otherwise - love when I can outsource the setup

**Comment by asiripanich** [comment]
Hi @raisin-toast, thank you for reporting this issue. I was not aware that there is another naming convention. Are you using a general release or a restricted release? (not sure if this matters but I have never used a general release.)

> I'd suggest making it agnostic to whatever letter the files end in.

Sounds good to me.

> Happy to submit a pr if it would help.

That would be fantastic.

> P.S. this looks like a great package otherwise - love when I can outsource the setup

Thanks!

**Comment by raisin-toast** [comment]
I am using the general release. Looking at my colleagues files, it looks like general release = c, and restricted = u. I'll have a go at fixing it and will put up a pr.
